// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCGrBsj4mphVWDUqy_a0YjrGi-gNk2Pu0',
    appId: '1:125027096524:web:9bd44f4a30975402c1ef69',
    messagingSenderId: '125027096524',
    projectId: 'minimart-77776',
    authDomain: 'minimart-77776.firebaseapp.com',
    storageBucket: 'minimart-77776.firebasestorage.app',
    measurementId: 'G-BKGJM1SJND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj1WIH4D5-6g2uZo5w_bj8iCHTvJaceNY',
    appId: '1:125027096524:android:94cfe46225743ad4c1ef69',
    messagingSenderId: '125027096524',
    projectId: 'minimart-77776',
    storageBucket: 'minimart-77776.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBygTavvSq7_VJGYFNinoFfOkzUKZ4pCNw',
    appId: '1:125027096524:ios:031963ebbf368af6c1ef69',
    messagingSenderId: '125027096524',
    projectId: 'minimart-77776',
    storageBucket: 'minimart-77776.firebasestorage.app',
    iosBundleId: 'com.example.minimart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBygTavvSq7_VJGYFNinoFfOkzUKZ4pCNw',
    appId: '1:125027096524:ios:031963ebbf368af6c1ef69',
    messagingSenderId: '125027096524',
    projectId: 'minimart-77776',
    storageBucket: 'minimart-77776.firebasestorage.app',
    iosBundleId: 'com.example.minimart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCGrBsj4mphVWDUqy_a0YjrGi-gNk2Pu0',
    appId: '1:125027096524:web:39452b9612fd53a6c1ef69',
    messagingSenderId: '125027096524',
    projectId: 'minimart-77776',
    authDomain: 'minimart-77776.firebaseapp.com',
    storageBucket: 'minimart-77776.firebasestorage.app',
    measurementId: 'G-9FHSBX3BNW',
  );
}
